#pragma once

enum XACT_WAVEBANK_AUDIO : unsigned int
{
    XACT_WAVEBANK_AUDIO_BUTTON = 0,
    XACT_WAVEBANK_AUDIO_CLAP = 1,
    XACT_WAVEBANK_AUDIO_FINISH = 2,
    XACT_WAVEBANK_AUDIO_FINISHGONG = 3,
    XACT_WAVEBANK_AUDIO_HIGHSCORE = 4,
    XACT_WAVEBANK_AUDIO_HITJELLY = 5,
    XACT_WAVEBANK_AUDIO_IMPACT = 6,
    XACT_WAVEBANK_AUDIO_JUMP = 7,
    XACT_WAVEBANK_AUDIO_PLAYBGM = 8,
    XACT_WAVEBANK_AUDIO_RESULTBGM = 9,
    XACT_WAVEBANK_AUDIO_SELECTMENU = 10,
    XACT_WAVEBANK_AUDIO_TITLEBGM = 11,
};

#define XACT_WAVEBANK_AUDIO_ENTRY_COUNT 12
